// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzrYa6D2w8X-93afLkKN7fI_EkN1Dg620',
    appId: '1:574293231:ios:266f68bf4084fddff8c71a',
    messagingSenderId: '574293231',
    projectId: 'authtutorial-630a5',
    storageBucket: 'authtutorial-630a5.appspot.com',
    iosBundleId: 'com.example.shoppro',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvciM9qTv0WRL7XgjXqHH-enPW8D16HPM',
    appId: '1:574293231:web:477919fa69eaebf2f8c71a',
    messagingSenderId: '574293231',
    projectId: 'authtutorial-630a5',
    authDomain: 'authtutorial-630a5.firebaseapp.com',
    storageBucket: 'authtutorial-630a5.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzrYa6D2w8X-93afLkKN7fI_EkN1Dg620',
    appId: '1:574293231:ios:266f68bf4084fddff8c71a',
    messagingSenderId: '574293231',
    projectId: 'authtutorial-630a5',
    storageBucket: 'authtutorial-630a5.appspot.com',
    iosBundleId: 'com.example.shoppro',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBZ1vJT468Qr0zSd6Rj49-vZwV0KNKXCk',
    appId: '1:574293231:android:92a87f13041f1b2cf8c71a',
    messagingSenderId: '574293231',
    projectId: 'authtutorial-630a5',
    storageBucket: 'authtutorial-630a5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvciM9qTv0WRL7XgjXqHH-enPW8D16HPM',
    appId: '1:574293231:web:8cd1b4dd042fd113f8c71a',
    messagingSenderId: '574293231',
    projectId: 'authtutorial-630a5',
    authDomain: 'authtutorial-630a5.firebaseapp.com',
    storageBucket: 'authtutorial-630a5.appspot.com',
  );

}